<?php

/**
 * Implements hook_menu().
 */
function kernel_menu() {
  $items = array();
  $items['bundles'] = array(
    'page callback' => 'kernel_assets_callback',
    'access callback' => TRUE,
    'file' => 'kernel.pages.inc',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * @param $name
 * @return array
 */
function kernel_info($name = 'app') {
  // Use the advanced drupal_static() pattern, since this is called very often.
  static $drupal_static_fast;
  if (!isset($drupal_static_fast)) {
    $drupal_static_fast['cache'] = &drupal_static(__FUNCTION__);
  }
  $cache = &$drupal_static_fast['cache'];

  if (!isset($cache)) {
    $cache = module_invoke_all('kernel_info');

    // Allow modules to alter the element type defaults.
    drupal_alter('kernel_info', $cache);
  }

  return isset($cache[$name]) ? $cache[$name] : array();
}

/**
 * @param string $name
 * @return \Symfony\Component\HttpKernel\KernelInterface
 */
function kernel_app($name = 'app') {
  static $kernel;
  $info = kernel_info($name);
  if (!$kernel) {

    if (is_array($info['require_once'])) {
      $files = array_filter($info['require_once'], 'file_exists');
      if (!empty($files)) {
        foreach ($files as $file) {
          require_once $file;
        }
      }
    }

    if ($info['arguments'][1]) {
      \Symfony\Component\Debug\Debug::enable();
    }

    if (class_exists($info['kernel class'])) {

      /* @var \Symfony\Component\HttpKernel\HttpKernelInterface $kernel */
      if (!empty($info['arguments']) && is_array($info['arguments'])) {
        $reflect = new ReflectionClass($info['kernel class']);
        $kernel = $reflect->newInstanceArgs($info['arguments']);
      }
      else {
        $kernel  = new $info['kernel class']();
      }

      foreach ($info['calls'] as $method => $args) {
        call_user_func_array(array($kernel, $method), $args);
      }

      return $kernel;
    }
  }
}

/**
 * Captures the response from the page callback for use in kernel_exit().
 */
function kernel_response(\Symfony\Component\HttpFoundation\Response $response = NULL) {
  $static = &drupal_static('kernel_response');
  if (isset($response)) {
    $static = $response;
  }
  else {
    return $static;
  }
}

/**
 * Implements hook_exit().
 */
function kernel_exit() {
  $kernel = kernel_app();
  $response = kernel_response();
  if ($response && is_a($kernel, 'Symfony\Component\HttpKernel\TerminableInterface')) {
    $router_item = menu_get_item();
    $request = $router_item['page_arguments'][0];
    /** @var \Symfony\Component\HttpKernel\TerminableInterface $kernel */
    $kernel->terminate($request, $response);
  }
}

/**
 * Implements hook_init().
 */
function kernel_init() {
  $kernel = kernel_app();
  if ($kernel) {
    $kernel->boot();
    $request = \Symfony\Component\HttpFoundation\Request::createFromGlobals();
    /** @var \Symfony\Bundle\FrameworkBundle\Routing\Router $router */
    $router = $kernel->getContainer()->get('router');
    try {
      $path = current_path();
      $router->match(base_path() . $path);
      $router_item = array(
        'path' => $path,
        'page_callback' => 'kernel_callback',
        'page_arguments' => array($request),
        'delivery_callback' => '',
        'tab_parent' => '',
        'tab_root' => $path,
        'title' => '',
        'type' => MENU_CALLBACK,
        'include_file' => drupal_get_path('module', 'kernel') .'/kernel.pages.inc',
        'href' => $path,
        'tab_root_href' => $path,
        'tab_parent_href' => '',
        'access' => true,
        'original_map' => arg(NULL, $path),
        'map' => arg(NULL, $path),
      );

      // If the desire is to output a whole Symfony response, use:
      //

      // $router_item['page_callback'] = array($kernel, 'handle');
      // $router_item['page_arguments'] = array($request);
      // $router_item['delivery_callback'] = 'kernel_deliver_response';

      menu_set_item(NULL, $router_item);
    }
    catch (\Exception $e) {

    }
  }
}

/**
 * @see drupal_deliver_html_page
 */
function kernel_deliver_response(\Symfony\Component\HttpFoundation\Response $response) {
  $response->send();

  module_invoke_all('exit');

  // Commit the user session, if needed.
  drupal_session_commit();

  if (variable_get('cache', 0) && ($cache = drupal_page_set_cache())) {
    drupal_serve_page_from_cache($cache);
  }

  _registry_check_code(REGISTRY_WRITE_LOOKUP_CACHE);
  drupal_cache_system_paths();
  module_implements_write_cache();
  system_run_automated_cron();
  exit();
}
